In [61]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

from sklearn import tree, metrics, model_selection, preprocessing

 
 

df = pd.read_csv('iris.csv')

df.head(5) 

 

df['species_label'],i = pd.factorize(df['species'])

df['species'].unique() 

df['species_label'].unique() 

 

 


y = df['species_label']

X = df[['sepal.length', 'sepal.width']]

 

X_train, X_test, y_train,y_test = model_selection.train_test_split(X,y,test_size=0.3, random_state=0)

 

 
 

dtree = tree.DecisionTreeClassifier(criterion='entropy' , max_depth=3) 

dtree.fit(X_train, y_train) 

 
 

y_pred = dtree.predict(X_test) 

 

accuracy = metrics.accuracy_score(y_test, y_pred)

print('Accuracy: {:.2f}'.format(accuracy)) 

 

 
from sklearn.metrics import  confusion_matrix 

print(confusion_matrix(y_test, y_pred))

Accuracy: 0.67
[[16  0  0]
 [ 1  5 12]
 [ 0  2  9]]
